### ISSUE TITLE
Change SBML to enum

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#112]
Implement as enum
see #106 
This has to be done before the API will be defined (see #18 )

**Comment by matthiaskoenig** [comment]
@draeger 
I remember now the second reason.
There is no way to make an enum behave like a String. It always behaves like an enum class.

But I need the type Java.lang.String everywhere in my code to interact with Cytoscape attributes.
I have to be able to do
`SBML.NODE_TYPE_SPECIES` and get a String and not everytime use a cast or call the `toString` method. 
i.e. not `(String) SBML.NODE_TYPE_SPECIES` or `SBML.NODE_TYPE_SPECIES.toString()` 

```
String[] nodeTypes = {
				SBML.NODETYPE_SPECIES,
				SBML.NODETYPE_REACTION,
				SBML.NODETYPE_QUAL_SPECIES,
				SBML.NODETYPE_QUAL_TRANSITION,
				SBML.NODETYPE_FBC_GENEPRODUCT,
				SBML.NODETYPE_FBC_AND,
				SBML.NODETYPE_FBC_OR
			}; 
```

**Comment by matthiaskoenig** [comment]
I went with option 2 here:
http://stackoverflow.com/questions/6667243/using-enum-values-as-string-literals

**Comment by draeger** [comment]
Ok, was just a suggestion. What ever works best in your case.
