### ISSUE TITLE
SBML Files kept when networks got destroyed or new session started

### ISSUE THREAD

**Issue by tpfau** [matthiaskoenig/cy3sbml#141]
The current SBMLManager (or rather the Network2SBMLMapper, does simply store any encountered sbml file, regardless on whether a network gets destroyed or a new session started.
This causes some unintended effects:
1. when restarting a session and loading the same network, that session cannot be properly saved as cy3sbml now tries to store 2 copies of the same file, which cytoscape does not allow. 
2. it leads to "dead" sbmls being stored in the memory.

The first also happens, if the same sbml is imported twice.

From my understanding, a new session, should reset the behaviour of almost anything that is not global to its defaults, so SBMLManager should probably be a NetworkAboutToBeDestroyedListener which removes any network-ID that stems from a destroyed network from its mapping (I don't think it needs to listen to session events, since starting a new session destroys all networks, and if only listening to sessions, the duplicate sbml would also appear, when a network gets destroyed and reloaded).

Also, it might be an idea to add suffixes to the files saved by cy3sbml (to avoid duplicates).
What might be a possibility woudl be to have something like the following:
`
	/**
	 * Get a Temporary file with a given filename and a given extension.
	 * IF the file already exists, suffixes will be added.
	 * @param FileName - Filename of the Temporary file
	 * @param Extension - File extension of the temporary file.
	 * @return The Temporary File Object.
	 */
	public static File getTemporaryFile(String FileName, String Extension)
	{
		File target = new File(System.getProperty("java.io.tmpdir") + File.separator + CY3SBML_TEMP_FOLDER + FileName + Extension);
		int suffix = 0;
		while(target.exists())
		{
			target = new File(System.getProperty("java.io.tmpdir") + File.separator + CY3SBML_TEMP_FOLDER + File.separator + FileName + "_" + suffix + Extension);
			suffix++;
		}
		
		return target;
	}
`
This creates temporary files checking that the file does not exist, and those temporary files can then be saved by cy3sbml.

**Comment by matthiaskoenig** [comment]
Good point. Thanks for the feedback.

I am already listening to the SessionLoad and NetworkDestroy Events, but did not update the SBMLManager and mappers accordingly.

I will implement your suggestions and make the session saving more robust.
