### ISSUE TITLE
https://identifiers.org/ prefixes cannot be resolved as collection

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#297]
Errors in frontend of the form:
```
Unknown data collection: https://identifiers.org/sbo```
```
for all identifiers.org links starting with https

**Comment by kyxhik** [comment]
The frontend error persisted with certain SBO representation categories, mainly the information macromolecules.

This seemed to fix the error:
in SBMLBaseHTMLFactory, line 411:
replacing http://identifiers.org/ with http://identifiers.org/biomodels.sbo/

@matthiaskoenig @draeger
