### ISSUE TITLE
Cytoscape App Store: add the "systems biology" tag?

### ISSUE THREAD

**Issue by bdelepine** [matthiaskoenig/cy3sbml#312]
Hi all,

I noticed that the categories of [cy3sbml in the Cytoscape App Store](http://apps.cytoscape.org/apps/cy3sbml) are "data visualization, import, network generation, SBML". I wonder why the tag "[systems biology](http://apps.cytoscape.org/apps/with_tag/systemsbiology)" is not among those as it looks very relevant to me and that it seems quite popular (top10 or so). Is there a reason for that?

**Comment by matthiaskoenig** [comment]
@bdelepine No reason at all, just never thought about it. I added some more tags, among them systems-biology. Thanks for the input let me know if there is anything else.
Best M
