### ISSUE TITLE
Stoichiometry not displayed

### ISSUE THREAD

**Issue by bbarker** [matthiaskoenig/cy3sbml#329]
This may be a known issue or a problem with the model, or a user error (sorry if so); I don't see any stoichiometry information when inspecting reactions when looking at methionine metabolism (downloaded from biomodels: `BIOMD0000000698`). In this case, I'm looking at the METIN reaction (see sbml reaction snippet at the end of post).

![image](https://user-images.githubusercontent.com/916366/184363844-ae0abaeb-c0a4-4f3f-ad0a-ad1ca38e8b9e.png)

![image](https://user-images.githubusercontent.com/916366/184368296-30b4e061-409e-426d-8a7e-6b7f0c719773.png)

```xml
      <reaction id="METIN" metaid="COPASI21" name="METIN" reversible="false">
        <annotation>
          <COPASI xmlns="http://www.copasi.org/static/sbml">
            <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dcterms="http://purl.org/dc/terms/">
              <rdf:Description rdf:about="#COPASI21">
                <dcterms:created>
                  <rdf:Description>
                    <dcterms:W3CDTF>2018-05-08T15:34:43Z</dcterms:W3CDTF>
                  </rdf:Description>
                </dcterms:created>
              </rdf:Description>
            </rdf:RDF>
          </COPASI>
        </annotation>
              <listOfReactants>
          <speciesReference metaid="e608e673-0595-40df-b897-be1129a09056" species="Metin" stoichiometry="1"/>
        </listOfReactants>
        <listOfProducts>
          <speciesReference metaid="_72b83a53-3507-4a88-a084-8d22d3b5a28e" species="Methionine" stoichiometry="1"/>
        </listOfProducts>
        <kineticLaw metaid="_991b7d17-6128-4697-b6ca-22fc35259a5f">
          <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply>
              <times/>
              <ci> Compartment </ci>
              <ci> k1 </ci>
              <ci> Metin </ci>
            </apply>
          </math>
                  <listOfParameters>
            <parameter id="k1" metaid="_6d531aff-7e05-4272-a01f-530db4e3cea7" name="k1" value="1"/>
          </listOfParameters>
        </kineticLaw>
      </reaction>
      ```

**Comment by matthiaskoenig** [comment]
@bbarker Thanks for the feedback. The stoichiometry information is available and can be accessed via the edge table. By default the information is not mapped on the network to avoid clattering the visualization.
But you can easily map this on the network.
I.e. modify the edge style and map the edge "stoichiometry" column as a Passthrough Mapping on the Edge Label style property.

You can save the style and reuse it.

See screenshot attached
![image](https://user-images.githubusercontent.com/900538/184375960-3ec65c2d-2d22-479f-a144-303519ce9ea3.png)

Please close the issue if this solves your problem.
