### ISSUE TITLE
Bug parsing some MIRIAM identifiers (MIRIAM offline)

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#36]
Example: MODEL1401310002 (Kerkhoven2013 - Glycolysis and Pentose Phosphate Pathway in T.brucei - MODEL C in fructose medium (with glucosomal ribokinase))

Species : _13BPGA_g (_13BPGA_g)
BIOLOGICAL_QUALIFIER : BQB_IS_VERSION_OF 
!!! //identifiers.org/pubchem.compound/683 (http) !!!

Should be:
BIOLOGICAL_QUALIFIER : BQB_IS_VERSION_OF 17234 (http://identifiers.org/chebi/CHEBI)
Check if problem with model or reading.

**Comment by matthiaskoenig** [comment]
The cy3sbml part of the problem is resolved.
Looks like a problem with the MIRIAM webservice when resolving resources with a single location (bug reported).

**Comment by biomodels-net** [comment]
small remark, I have developed a small library that has the same API as the Miriam web services but is local. It is called miriam-common and use the xml export of the database.

**Comment by matthiaskoenig** [comment]
Thanks for the hint.
Can you link to the jar/source or maven dependencies?
Definitely interested in providing proper offline functionality and already
thought about using parsing the xml myself.
Matthias



On Wed, Jun 24, 2015 at 4:23 PM, Biomodels.net team <
notifications@github.com> wrote:

> small remark, I have developed a small library that has the same API as
> the Miriam web services but is local. It is called miriam-common and use
> the xml export of the database.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matthiaskoenig/cy3sbml/issues/36#issuecomment-114885186>
> .
>



-- 
---------------------------------------------------
Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450 528 197
Tel: + 49 176 81168480
---------------------------------------------------

**Comment by niko-rodrigue** [comment]
no maven dependencies, I think.

https://sourceforge.net/p/sbfc/code/HEAD/tree/trunk/lib/miriam-common-1.0.jar?format=raw

Latest sources are there svn+ssh://svn.code.sf.net/p/sbml/code/trunk/sbmleditor/src/uk/ac/ebi/miriam.


The API is exactly the same as the WS one with some extra methods so you should be able to use it very easily (I made sure it was passing the junit tests from the WS), the only think changing is how you initialize the main object:

    static private MiriamLocalProvider link;

    static {
        // Creation of the link to the Web Services
        // link = new MiriamLink();
        link = new MiriamLocalProvider();

        // Sets the address to access the Web Services
        // link.setAddress("http://www.ebi.ac.uk/miriamws/main/MiriamWebServices");

    }


It is searching for the xml file in several location which I am no sure which exactly but I always use it with an argument when launching the java program:
-Dmiriam.xml.export=somepath/miriam.xml 

We might want to modify the sources of MIRIAMDatabase to allow to initialize it with some different methods or to refresh it once a new export miriam.xml is downloaded.

**Comment by matthiaskoenig** [comment]
Perfect. I will try this. 
I wanted to handle the miriam.xml in the following way:
* on first startup just download the latest file and use it
* on later startups use the downloaded file and check in background if newer version (via hash) is available and replace the older file.
This would also solve the current offline issues (i.e. without internet/web service access) the annotations can currently not be resolved.
Thanks Nico.

**Comment by biomodels-net** [comment]
On 24/06/15 16:33, Matthias König wrote:

Perfect. I will try this.
I wanted to handle the miriam.xml in the following way:

  *   on first startup just download the latest file and use it
  *   on later startups use the downloaded file and check in background if newer version (via hash) is available and replace the older file. This would also solve the current offline issues (i.e. without internet/web service access) the annotations can currently not be resolved. Thanks Nico.

—
Reply to this email directly or view it on GitHub<https://github.com/matthiaskoenig/cy3sbml/issues/36#issuecomment-114912814>.

I finish most of the changes that I wanted to do on the registry lib.

It is commited there:
https://sourceforge.net/p/identifiers-org/code/HEAD/tree/registry-lib/

I will try to put a README.md file there to have a bit of documentation.

The class to read the xml export is org.identifiers.registry.RegistryDatabase and the class
that reproduce the API of the current web services is org.identifiers.registry.RegistryLocalProvider

I included a xml export file in the jar file to have a default all the time, then you have two methods to load
the database from a given file or InputStream in RegistryDatabase.

Have not done any pom file but I was thinking of using org.identifiers.registry for the group id
and registry-lib for the name. We will probably upload it to the ebi maven repo once we decide
that it's working properly.

cheers,
Nico

The Babraham Institute, Babraham Research Campus, Cambridge CB22 3AT Registered Charity No. 1053902.
The information transmitted in this email is directed only to the addressee. If you received this in error, please contact the sender and delete this email from your system. The contents of this e-mail are the views of the sender and do not necessarily represent the views of the Babraham Institute. Full conditions at: www.babraham.ac.uk<http://www.babraham.ac.uk/terms>

**Comment by matthiaskoenig** [comment]
The miriam web service bug is still not fixed (not sure if problem with the call). 
Move to the offline version for good now.

**Comment by matthiaskoenig** [comment]
This is so strange:
The following is resolved
```
<rdf:li rdf:resource="urn:miriam:kegg.compound:C00236"/>
```
but this not
```
<rdf:li rdf:resource="http://identifiers.org/kegg.compound/C00013" />
```
same problem for other rdf, but only if exactly 1 resource (?).

**Comment by matthiaskoenig** [comment]
This is fixed for now by directly using the http://identifiers.org links and only resolving urns

**Comment by matthiaskoenig** [comment]
This came up again in the context of #8 
To resolve the Ontology Lookup Service URIs it is necessary to get the OLS resources and than construct the api address from them.
Use Niko code with the xml of the MIRIAM resources
http://www.ebi.ac.uk/miriam/main/export/xml/
