### ISSUE TITLE
Escher layouts

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#42]
Use Escher layouts in combination with BIGG models
https://escher.github.io/

**Comment by matthiaskoenig** [comment]
Use cases for creating Escher layouts (SBML -> JSON via cobrapy)

**Comment by matthiaskoenig** [comment]
First version of Escher Converter is out
https://github.com/SBRG/EscherConverter/releases

**Comment by draeger** [comment]
That's actually the original version that was published together with the article a while ago. A new version can be expected by the end of August 2016 when the Google Summer of Code will terminate.
