### ISSUE TITLE
Cofactor nodes (secondary metabolites)

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#47]
Implement cofactor nodes based on SBO annotations & node degree.
Especially for larger networks this becomes a crucial feature to be able to work with the models.

**Comment by matthiaskoenig** [comment]
A subset of nodes can be defined as cofactors:
- these nodes are cloned (similar to clone markers in SBGN) resulting in a node degree of 1
- highly connected nodes are multiplied to reduce visual cluttering & improve layouts
```
['atp', 'adp', 'nad', 'nadh', 'nadp', 'nadph', 'gtp', 'gdp', 'h', 'coa', 'ump', 'h20', 'ppi']
```

**Comment by matthiaskoenig** [comment]
Core functionality implemented. 
Missing things are
- store cofactor nodes in Cytoscape session files (persistence)
- register cofactorClones in the node to SBML mapping (information display)
- positioning of nodes after cloning (better visualization)

**Comment by draeger** [comment]
Here is a list of further frequent co-factors: http://bmcsystbiol.biomedcentral.com/articles/10.1186/s12918-015-0212-9#Tab1.

**Comment by matthiaskoenig** [comment]
```
H2O(Water) C00001
Zn2+ (Zinc ion) C00038

Cu2+
	

Copper ion
	

C00070

Ca2+
	

Calcium ion
	

C00076

H+
	

Proton
	

C00080

Co2+
	

Cobalt ion
	

C00175

K+
	

Potassium ion
	

C00238

H2
	

Hydrogen
	

C00282

Ni2+
	

Nickel ion
	

C00291

Cl−
	

Chloride ion
	

C00698

HCl
	

Hydrochloric acid
	

C01327

H2Se
	

Hydrogen selenide
	

C01528

Fe2+
	

Iron (II) ion
	

C14818

Fe3+
	

Iron (III) ion
	

C14819

**Comment by matthiaskoenig** [comment]
First draft of cofactors:
https://github.com/matthiaskoenig/cy3sbml/blob/develop/src/main/resources/cofactors/cofactors.json
Now all Kegg & Chebis or other annotations have to be looked up.

**Comment by matthiaskoenig** [comment]
@draeger 
Thanks for the sbmlsqueezer cofactors. 
Here a first full cofactor list with KEGG & Chebi annotations.
https://github.com/matthiaskoenig/cy3sbml/blob/develop/src/main/resources/cofactors/cofactors.json
There where some smaller bugs in Table 1:
* Ni2+ C00291 -> C19609 (KEGG Ni atom instead of Ni2+ entry annotated)
* Mo2+ (does not exist, only Mo4+ | Mo5+, no KEGG entry for either, only for Mo atom C00150)
* Mg2+ (missing from table, important ion especially in complexation with ATP)

**Comment by matthiaskoenig** [comment]
* Associate SBML to cofactor nodes
* make feature stable & test 
* provide simple option for provided cofactor list

**Comment by matthiaskoenig** [comment]
SBMLObjects are not mapped to the cofactor nodes, so no information is displayed.
Also consider a clone marker.

**Comment by matthiaskoenig** [comment]
Undoing cloning not working correctly, i.e. all clones are undone.
