### ISSUE TITLE
[annotation] Display non-standard annotation information

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#64]
Display the annotation xml which are not CV terms.
I.e. provide access to the non-standard annotations.

**Comment by draeger** [comment]
How do you want to do that? It can be anything. The simplest way would probably be to provide some direct text-editing feature.

**Comment by matthiaskoenig** [comment]
Hi Andreas,
the idea is to take the annotation xml, get the subset of xml which are not the cv terms and display the xml as is, with hyperlinks to all http links in the annotations.

Per definition the annotation is:
{ Any well-formed XML content, and with each top-level
element placed in a unique XML namespace; see text. }

I just got a model on my table which had the following annotation which would be very interesting to see when clicking on the element
```
<annotation>
      <listOfControlledVocabularies>
        <controlledVocabularyReference type="organism" location="http://stke.sciencemag.org/cm/vocabularies/organism.xml" />
        <controlledVocabularyReference type="tissue_cell" location="http://stke.sciencemag.org/cm/vocabularies/tissue_cell.xml" />
        <controlledVocabularyReference type="relation_method" location="http://stke.sciencemag.org/cm/vocabularies/relation_method.xml" />
        <controlledVocabularyReference type="species_type" location="http://stke.sciencemag.org/cm/vocabularies/species_type.xml" />
        <controlledVocabularyReference type="subcellular_localization" location="http://stke.sciencemag.org/cm/vocabularies/subcellular_localization.xml" />
      </listOfControlledVocabularies>
      <pathway componentLibrary="http://stke.sciencemag.org/component_library.xml" userLibrary="http://stke.sciencemag.org/user_library.xml">
        <description>The heterotrimeric guanine nucleotide-binding protein (G protein) G&lt;sub&gt;s&lt;/sub&gt; pathway leads to activation of adenylyl cyclases (ACs) and increased concentrations of adenosine 3',5'-monophosphate (cAMP).</description>
        <listOfAuthorities>
          <authority userid="pram" corresponding="0" />
          <authority userid="iyengar" corresponding="1" />
        </listOfAuthorities>
        <auditing authorityID="iyengar" createdBy="iyengar" creationDate="2000-09-27 09:24:58.28" lastModifiedBy="ngough" lastModifiedDate="2006-08-01 07:54:23.573" />
      </pathway>
    </annotation>
```
It would be nice to just display this as above, i.e. grey background, with the links clickable. For the display I would remove the <rdf:RDF> XML annotation elements.

**Comment by draeger** [comment]
Ok, that's the most straightforward way to deal with it.

However, I am wondering what annotation this is. Your example is lacking a proper namespace declaration and most of what I see there should better go into MIRIAM annotations. Some of it, such as the creation and modification date, has direct support in regular standardized SBML (history element) all other aspects can also be expressed in a much better way.

Would you reveal where this originates from? If all the annotations you are dealing with are like that it would be much better to translate them to something that is more easily readable. MIRIAM annotations have all the parsers and data structures available already. For this, we have to write something special and it is doing the same...

**Comment by matthiaskoenig** [comment]
Yes, I agree. These should be handled via MIRIAM annotations. 

Not sure with what the file was created with, but looked like some SBML supporting software with a custom way to store information in the annotation (got send to me in a bug report). 
These seems somehow related to Science Signalling
http://stke.sciencemag.org/
I send you the file by email.

There are quit a lot of tools writing custom annotation information into SBML. It would be nice to at least see the xml information for that (for instance CellDesigner).

**Comment by matthiaskoenig** [comment]
Not important. Will be reopened if feature is requested.
