### ISSUE TITLE
Read annotation in node columns

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#65]
Read SBML annotations in columns for the nodes.
Create single column for every Miriam annotation.

**Comment by niko-rodrigue** [comment]
It case it can be useful, the CobraUtils class in jsbml contain a method to parse
    the SBML notes into a java Properties object.

**Comment by matthiaskoenig** [comment]
Perfect. You already implemented what I need.
Thanks.

On Mon, Nov 30, 2015 at 11:21 AM, Nicolas Rodriguez <
notifications@github.com> wrote:

> It case it can be useful, the CobraUtils class in jsbml contain a method
> to parse
> the SBML notes into a java Properties object.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matthiaskoenig/cy3sbml/issues/65#issuecomment-160588596>
> .
>



-- 
--------------------------------------------------------------
Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450528449
Tel: + 49 176 81168480
--------------------------------------------------------------

**Comment by draeger** [comment]
Hi guys,

BiGG Models database now uses the groups package for subsystems. It would be great if CySBML would also understand this.

Cheers
Dr. Andreas Dräger
Bioengineering Dept., Systems Biology Research Group
University of California, San Diego, La Jolla, CA 92093-0412, USA
Phone: +49-7071-29-78982, Fax: +49-7071-29-5091, twitter: @dr_drae


> Am 30.11.2015 um 11:24 schrieb Matthias König <notifications@github.com>:
> 
> Perfect. You already implemented what I need.
> Thanks.
> 
> On Mon, Nov 30, 2015 at 11:21 AM, Nicolas Rodriguez <

**Comment by matthiaskoenig** [comment]
Hi Andreas,
this is very nice.
I will implement this in combination with the COBRA subsystems.
M

On Mon, Nov 30, 2015 at 11:54 AM, Andreas Dräger <notifications@github.com>
wrote:

> Hi guys,
>
> BiGG Models database now uses the groups package for subsystems. It would
> be great if CySBML would also understand this.
>
> Cheers
> Dr. Andreas Dräger
> Bioengineering Dept., Systems Biology Research Group
> University of California, San Diego, La Jolla, CA 92093-0412, USA
> Phone: +49-7071-29-78982, Fax: +49-7071-29-5091, twitter: @dr_drae
>
>
>
> > Am 30.11.2015 um 11:24 schrieb Matthias König <notifications@github.com
> >:
> >
> > Perfect. You already implemented what I need.
> > Thanks.
> >
> > On Mon, Nov 30, 2015 at 11:21 AM, Nicolas Rodriguez <
> > notifications@github.com> wrote:
> >
> > > It case it can be useful, the CobraUtils class in jsbml contain a
> method
> > > to parse
> > > the SBML notes into a java Properties object.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matthiaskoenig/cy3sbml/issues/65#issuecomment-160596552>
> .
>



-- 
--------------------------------------------------------------
Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450528449
Tel: + 49 176 81168480
--------------------------------------------------------------

**Comment by matthiaskoenig** [comment]
The core functionality is implemented, but it should be handled in a separate Table (AnnotationTable) to not pollute the  SBML Data Table.
