### ISSUE TITLE
[sbml-groups] Support BiGG groups / groups package

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#70]
Hi guys, 
BiGG Models database now uses the groups package for subsystems. 
It would be great if CySBML would also understand this. 

Cheers Dr. Andreas Dräger Bioengineering Dept., Systems Biology Research Group University of California, San Diego, La Jolla, CA 92093-0412, USA Phone: +49-7071-29-78982, Fax: +49-7071-29-5091, twitter: 

Separated from
#65

**Comment by matthiaskoenig** [comment]
Implement groups support

**Comment by draeger** [comment]
Well done. Until now, we don't have a specific SBO term, but our groups have the kind partonomy and only comprise reactions. It should therefore be straightforward to recognize them.

**Comment by matthiaskoenig** [comment]
Yes, will interpret them as a special group (should be easy to detect).
Wanted to implement this in the next few days.

On Fri, Mar 11, 2016 at 7:57 PM, Andreas Dräger <notifications@github.com>
wrote:

> Well done. Until now, we don't have a specific SBO term, but our groups
> have the kind partonomy and only comprise reactions. It should therefore be
> straightforward to recognize them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matthiaskoenig/cy3sbml/issues/70#issuecomment-195498074>
> .
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480

**Comment by matthiaskoenig** [comment]
Groups will be implemented using the Cytoscape groups package:
http://chianti.ucsd.edu/cytoscape-3.4.0/API/org/cytoscape/group/package-summary.html
