### ISSUE TITLE
Save state/SBMLDocuments in session

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#73]
Necessary to provide the option to save the SBMLDocuments with the Cytoscape session file and be able to restore it.

**Comment by draeger** [comment]
You might think of just serializing it because all JSBML objects are instances of [Serializable](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html).

**Comment by matthiaskoenig** [comment]
I will go with the serializing if it is to complicated to write the SBML. But it should be straight-forward because all the changes are on the SBMLDocument, so can just write them out. This has the advantage that there are real '.xml' SBML files in the session file, so some other tool can just extract the session file and use the SBML.
The main challenge is to write out and restore the SBMLDocument2CytoscapeNetwork mapper, i.e. which networks are linked to which SBMLDocuments.

The main idea behind this issue is that one is able to exchange the session files without the need to have also the SBML and to read them in. One can just stop working on a Cytoscape session with cy3sbml and save the state (especially layouts, subnetworks, visual mappings, ...).

**Comment by matthiaskoenig** [comment]
This is implemented.
Remaining issues are related to serialization/deserialization of SBMLDocuments in JSBML. 
see https://groups.google.com/forum/#!topic/jsbml-development/0wuXvQZ0WG0

**Comment by matthiaskoenig** [comment]
Fixed in JSBML revision 2491
