### ISSUE TITLE
RateRules and AssignmentRules miss derivedUnits

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#89]
The derivedUnits are not parsed.

**Comment by draeger** [comment]
This is unclear, because derived units are actually not in the model file, but derived at runtime. How would you parse them?

**Comment by matthiaskoenig** [comment]
Sorry the description was unclear.  I forgot to write the derived units in the node table of cytoscape. 
They can be derived from the model, but where just not written in the tables when parsing the SBML.
